release:
  product: gto
  primary_project_id: 16320
  current_version: 0.5.4

projects:
  - locale: en_us
    project_id: 16320
    allowed_stages: [-1, 5, 9]
  - locale: ru_ru
    project_id: 16525
    allowed_stages: [-1, 5, 9]
  - locale: ja_jp
    project_id: 18185
    allowed_stages: [-1, 1, 3, 5, 9]
